// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NutriTrack.Domain.Data;

#nullable disable

namespace NutriTrack.Domain.Migrations
{
    [DbContext(typeof(NutriTrackDbContext))]
    partial class NutriTrackDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("domain")
                .HasAnnotation("ProductVersion", "8.0.27");

            modelBuilder.Entity("NutriTrack.Domain.Entities.Ingredient", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Note")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Ingredients", "domain");
                });

            modelBuilder.Entity("NutriTrack.Domain.Entities.IngredientMicronutrient", b =>
                {
                    b.Property<Guid>("IngredientId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("MicronutrientId")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("AmountPer100g")
                        .HasColumnType("decimal(18,4)");

                    b.HasKey("IngredientId", "MicronutrientId");

                    b.HasIndex("MicronutrientId");

                    b.ToTable("IngredientMicronutrients", "domain");
                });

            modelBuilder.Entity("NutriTrack.Domain.Entities.MealLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("AmountInGrams")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("EatenAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("EatenByUserId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("IngredientId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Note")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("RecipeId")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("Servings")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("EatenAt");

                    b.HasIndex("EatenByUserId");

                    b.HasIndex("IngredientId");

                    b.HasIndex("RecipeId");

                    b.ToTable("MealLogs", "domain");
                });

            modelBuilder.Entity("NutriTrack.Domain.Entities.Micronutrient", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("DailyReferenceAmount")
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Note")
                        .HasColumnType("TEXT");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Micronutrients", "domain");
                });

            modelBuilder.Entity("NutriTrack.Domain.Entities.Recipe", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<string>("PrepNote")
                        .HasColumnType("TEXT");

                    b.Property<string>("YouTubeUrl")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Recipes", "domain");
                });

            modelBuilder.Entity("NutriTrack.Domain.Entities.RecipeIngredient", b =>
                {
                    b.Property<Guid>("RecipeId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("IngredientId")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("AmountInGrams")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("RecipeId", "IngredientId");

                    b.HasIndex("IngredientId");

                    b.ToTable("RecipeIngredients", "domain");
                });

            modelBuilder.Entity("NutriTrack.Domain.Entities.IngredientMicronutrient", b =>
                {
                    b.HasOne("NutriTrack.Domain.Entities.Ingredient", "Ingredient")
                        .WithMany("IngredientMicronutrients")
                        .HasForeignKey("IngredientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NutriTrack.Domain.Entities.Micronutrient", "Micronutrient")
                        .WithMany("IngredientMicronutrients")
                        .HasForeignKey("MicronutrientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ingredient");

                    b.Navigation("Micronutrient");
                });

            modelBuilder.Entity("NutriTrack.Domain.Entities.MealLog", b =>
                {
                    b.HasOne("NutriTrack.Domain.Entities.Ingredient", "Ingredient")
                        .WithMany()
                        .HasForeignKey("IngredientId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("NutriTrack.Domain.Entities.Recipe", "Recipe")
                        .WithMany()
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Ingredient");

                    b.Navigation("Recipe");
                });

            modelBuilder.Entity("NutriTrack.Domain.Entities.RecipeIngredient", b =>
                {
                    b.HasOne("NutriTrack.Domain.Entities.Ingredient", "Ingredient")
                        .WithMany("RecipeIngredients")
                        .HasForeignKey("IngredientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NutriTrack.Domain.Entities.Recipe", "Recipe")
                        .WithMany("RecipeIngredients")
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ingredient");

                    b.Navigation("Recipe");
                });

            modelBuilder.Entity("NutriTrack.Domain.Entities.Ingredient", b =>
                {
                    b.Navigation("IngredientMicronutrients");

                    b.Navigation("RecipeIngredients");
                });

            modelBuilder.Entity("NutriTrack.Domain.Entities.Micronutrient", b =>
                {
                    b.Navigation("IngredientMicronutrients");
                });

            modelBuilder.Entity("NutriTrack.Domain.Entities.Recipe", b =>
                {
                    b.Navigation("RecipeIngredients");
                });
#pragma warning restore 612, 618
        }
    }
}
